# Generated by Django 4.2.4 on 2023-08-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('number', models.TextField()),
                ('otp', models.TextField()),
                ('time', models.DateTimeField()),
                ('token', models.TextField()),
                ('profile', models.ImageField(upload_to='')),
            ],
        ),
    ]
